### PR TITLE
Deleted logo.png

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by coyotte508** [comment]
This isn't used anywhere in the webclient though?

**Comment by danimesq** [comment]
I don't know. But here is the new logo with the flat old blue pokeball icon.

**Comment by coyotte508** [comment]
imo it can be removed altogether, and added later if needed.

**Comment by danimesq** [comment]
I think that update it and use when needed is better.
It can be used in server list.

**Comment by coyotte508** [comment]
server list is `po-registry`.

**Comment by danimesq** [comment]
Done, @coyotte508

**Pull request merged**
