### PR TITLE
Show playercount in channels

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by coyotte508** [comment]
Can you put a screenshot to see?

**Comment by danimesq** [comment]
Done, added.

**Comment by coyotte508** [comment]
That place is something limited for mobile users or users with a lot of channels open. Even then, the player count shows the users in current channel, and in battles or pms it'd be 2, plus it doesn't look especially good. All those are reasons why it's hidden in the first place.

**Comment by danimesq** [comment]
The solution is define it to work only in channels, not in PMs.

**Comment by coyotte508** [comment]
I just tested it - and it doesn't look nice.

BUT, a solution that would be good and useful is to put it in the channel name? In grey (maybe in a grey badge) next to the channel's name. But then you'd have to add code so it checks every channel.

**Pull request closed without merging**
