### PR TITLE
PNG Compression

### PR DESCRIPTION
**Pull request by MidwayMarshall**
images folder reduced to 124/188KB

### CODE REVIEW

**Comment by coyotte508** [comment]
Only the background needs compressing.

The pokeballs are very widely used and don't weight much, I am of a mind to leave them as is.

**Comment by MidwayMarshall** [comment]
I don't see a reason not to remove unused color space from 10 color images.
But I'll rebase with just the background

**Comment by coyotte508** [comment]
well I don't know how you did it. If it's truly absolutely lossless then there's no problem.

**Comment by MidwayMarshall** [comment]
I removed unneeded\* color space (2,4,8,16,32,64,128,256 different colors possible for 8bit png)
So if it needs between 9-16 colors I set it to use a palette of 16.
http://i.imgur.com/AHTwLmd.png
1.28 kbytes image vs 292 bytes

Github has some nice ways to see any differences in the files changed tab

**Comment by coyotte508** [comment]
I stand corrected !

**Pull request merged**
