### PR TITLE
Fix "...was dragged out" message (hopefully)

### PR DESCRIPTION
**Pull request by turbedi**
Can someone look over it/test it and tell me if it is working?

### CODE REVIEW

**Comment by IceKirby** [comment]
What is this error? I tested the "dragged out" message and it displays the name properly even without this commit (the Pokémon's name seems to be %f, which is already covered, not %e).

**Comment by turbedi** [comment]
https://github.com/po-devs/pokemon-online/commit/c8201d45261a577a78cd9eebb221b92d394b749e
It should use the Pokémon's name and not the nickname. I didn't test the current behavior of the webclient, but I assumed that it uses the nickname like the Windows-Client did.

**Comment by turbedi** [comment]
I forgot to update the move_message file to use %e. (fixed now)

**Comment by Fuzzysqurl** [comment]
sulcata added this

**Pull request closed without merging**
