### PR TITLE
Show player kicks/bans

### LINKED ISSUE #18: Show player kicks / tempbans / bans
When a player right click someone (on computer client) and does so, the message doesn't show on webclient.

The network commands are:
- `playerkick` with `source` and `target`
- `playerban` with `source` and `target` and optional `time` in seconds

Todo: Edit `network.js` to add parsers for those, print with `webclientUI.printHtml(msg)`.

### PR DESCRIPTION
**Pull request by jinorae**
Shows playerkick and playerban events.

fixes #18 

let me know if theres any style stuff that should be changed (like if the code should be in backend.js instead of network.js)

### CODE REVIEW

**Comment by coyotte508** [comment]
Instead of `<b><span style='color: red;'>` it should be `<span class='player-kick'>` and `<span class='player-ban'>` with both of those added in `app/assets/stylesheets/chat.less`.

(`grunt less` should be run afterwards to properly update the .css file when testing)

**Comment by jinorae** [comment]
ok, and should they be in network.js or calling a separate function in backend.js?

**Comment by coyotte508** [comment]
The code is fine here.

**Comment by jinorae** [comment]
fixed.

**Comment by coyotte508** [comment]
you need to call `utils.escapeHtml()` on the player names as well!

**Comment by jinorae** [comment]
fixed!

**Pull request merged**
