### PR TITLE
Separated categories in Settings dropdown menu

### PR DESCRIPTION
**Pull request by danimesq**
After:

Before:

### CODE REVIEW

**Comment by coyotte508** [comment]
Can you show a screenshot compared to the current version?

**Comment by danimesq** [comment]
Done, added.

**Comment by coyotte508** [comment]
It's big - especially on mobile. 

And there's two categories with only one item...

**Comment by danimesq** [comment]
In mobile the menu is not even shown:


And the categories with only one item are waiting for new items that can be implemented.

**Comment by coyotte508** [comment]
Then when new (too many) items are implemented we may even do another dropdown for each category. It's different from this solution.

**Comment by danimesq** [comment]
Why each dropdown for each category if we can use a tab menu in only one dropdown? :smiley:

**Comment by coyotte508** [comment]
For more info, if it's not added in the bootstrap theme, it's not something twitter's designer thought cool.

Also, using h4 separated from all the li things in an ul must be something browser designers would hate you for.

I don't understand your last comment ^^

**Comment by danimesq** [comment]
I don't understand why use a bunch dropdowns if we can use only one with a simple tab menu separating the categories for objective and easy UX.

**Comment by coyotte508** [comment]
If we add more items per categories as you said, then there'll be a lot less space. If there's too many things, then it can't be put all in one list.

It doesn't have to be dropdowns, instead it can be buttons (like in FF's menu) that open other settings windows.

Anyway, even google chrome which surely does a lot of research doesn't do it this way but uses simple separators.

(and they have a dropdown "more tools")

**Pull request closed without merging**
