### PR TITLE
Usernames in chat supporting right click for show context menu (#140)

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by coyotte508** [comment]
Current changes just disable right click

**Comment by danimesq** [comment]
Sorry. I'll review it.

**Comment by DaniellMesquita** [comment]
@coyotte508 Updated.

**Comment by danimesq** [comment]
@coyotte508:

> Current changes just disable right click

And now?

**Comment by coyotte508** [comment]
you can't do id = "player-XXX" on chat messages. It risks conflicting with other stuff and [ids are supposed to be unique](http://programmers.stackexchange.com/questions/127178/two-html-elements-with-same-id-attribute-how-bad-is-it-really). Here if somebody speaks 5 times there's 5 items with the same id.

**Comment by danimesq** [comment]
How can I'll identify users to prompt context menu?

**Comment by coyotte508** [comment]
by doing `$(this).attr("pid");` (id must be unique but pid is fine)

Anyway did you test it? from the code it doesn't seem that there's a special handler for names in the chat to say to use custom context menus.

**Comment by coyotte508** [comment]
Since OP left the project, new code is unlikely to be added

**Pull request closed without merging**
