### PR TITLE
Changed base color (based on pokeball icon)

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by coyotte508** [comment]
It's an issue that changes the **color of the whole theme**.

Maybe a screenshot is required for such a major change?

Also since it's a simple one line edit, maybe before creating the issue, posting in #general with the screenshots to get ideas and opinions before creating the issue?

Issues are supposed to be stuff that need to be done, not suggestions. If you don't know, or if the issue seems like it may not be needed, asking in the discord chat is a good idea.

Me testing every issue, closing some of them and making justifications for each one takes a lot of time. If an issue is closed, it happens once sometimes. But it shouldn't happen several times per day.

**Comment by danimesq** [comment]
Why usea main theme color different than the used in pokeball? This actual theme was made to fit with the globe logo/icon, and not match the actual visual identy.

**Comment by coyotte508** [comment]
At least show a screenshot for something that changes the whole goddamn theme. Do you expect someone to just click merge with no comment, a one line edit with major changes like that?

If no screenshot I have to test it, but that's not even the main thing, others don't see and can't give their opinions.

**Comment by danimesq** [comment]
Sorry. Updated.

**Pull request closed without merging**
