### PR TITLE
Emojis

### PR DESCRIPTION
**Pull request by HearkOld**
filters msg string for emoticons and replaces them with matching emojis

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
Make it optional. Emojis are gross :)

**Comment by coyotte508** [comment]
Too many commits in the pull request.

http://www.emoji-cheat-sheet.com/

May as well do all that!

https://discord.gg/010O1SggVDA5ZTBSc <- If you want to talk.

**Comment by danimesq** [comment]
@coyotte508

> Too many commits in the pull request.

@Fuzzysqurl ever does merge+squish, then this is not a problem in this case. Btw, good see your return, Coyo :smile:

**Comment by sulcata** [comment]
Definitely should be an option to turn it off (or even make it off by default). I know a lot of people on PO seem to dislike them in the chat and on forums. Also perhaps it's just me but it feels like it goes against the clean design we currently have.

**Comment by HearkOld** [comment]
I'll just put this on hold, if coyo or anyone wants it implemented I'll add toggle options.

**Comment by danimesq** [comment]
@coyotte508 what do you think?

**Pull request closed without merging**
