### PR TITLE
Build icons & new favicon

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by sulcata** [comment]
Bold looks a bit goofy with the lean'n'clean look of the webclient :x

**Comment by danimesq** [comment]
My intention is pair a few design things with the Desktop client. Some things I agree with inovation, such as the username in bar and the buttons, yes. But the userlist will not be goofy and can be keep from Desktop's design.

**Comment by danimesq** [comment]
Usernames need be bold. You see in our comments in GitHub? Our usernames are in bold! ;)

**Comment by sulcata** [comment]
That's not a player list though. Your username isn't already differentiated from the title so it seems appropriate to bold it. The bold font for the player list is quite heavy to be honest. Also the desktop doesn't have a bold player list unless you're using a custom style.

I don't think we should really be focusing on copying the desktop's design. The webclient has an extremely clean look that I think makes it much better than the desktop client and PS.

**Comment by danimesq** [comment]
Very good/valid arguments. In my opinion (not reason) I preffer bold in user list. Lets see what the rest of developers think about.

**Comment by danimesq** [comment]
I agree the design of WebClient is better, but the Desktop have a few objects that don't have in WebClient, such as a advanced interface for "Find battle", the current version in bottom, the server's HTML intro, etc. I'll focuse in make WebClient better and put the best Desktop's functions (in which the bold is not a part).

**Comment by danimesq** [comment]
@Sulcata, what do you think about the new background and white foreground?

**Comment by aurist** [comment]
There could be an option for people to allow background images like that if ppl are willing to implement that? Similar to PS' background images I suppose. Also yeah that picture would need cropping

**Comment by danimesq** [comment]
The best option is as default have the clean background and user can activate "more-colored" backgrounds. If activated, each server can set your own background, and user can overide it by setting your own background or enabling/disabling "colorfull-background" feature. Will be a more sensate decision.

**Comment by danimesq** [comment]
Renewed splashscreen:

**Comment by sulcata** [comment]
I don't think we should be hotlinking those images.

Also I think I've heard that solid, bright blue on computer screens isn't easy on the eyes. I don't think it matches the webclient theme either.

**Comment by sulcata** [comment]
Also if we're going to be using an artist's background we should probably pay for one (I'm sure PO has enough for that?) or at least get permission or something like that.

**Comment by danimesq** [comment]
Why pay for a background? We can have people to donate background permissions or create one from scratch. Regarding to splashscreen, is only a test. I'll ask for pikachu's gif creator for give permissions (or see his license). Regarding to splashscreen's blue color, this is focused in the Windows 10 app build, and I'll add codes to separate it.

**Comment by danimesq** [comment]
Too, the permissions or see the license of the background (the "something like that"). @sulcata what do you think about foreground?

**Comment by DaniellMesquita** [comment]
Regarding to blue splashscreen, this is very strong. This need be more opaque/faded.

**Comment by danimesq** [comment]
Now, the new background has removed. As I've spoken: "The best option is as default have the clean background and user can activate "more-colored" backgrounds. If activated, each server can set your own background, and user can overide it by setting your own background or enabling/disabling "colorfull-background" feature. Will be a more sensate decision".

**Comment by danimesq** [comment]
Summary:
- [ ] Usernames in user list with bold weight;
- [x] Added Android icon to build folder;
- [x] Added WinUP icon to build folder;
- [x] Added Win32 icon to build folder;
- [x] Changed favicon;

Old favicon:


New favicon:


Android icon:

**Comment by danimesq** [comment]
The build folder is for universal app, for developers use different icons for different platforms.
The new favicon is generic-design, not mentioning Windows' design.

> @Sulcata [4 de mai de 2016 03:39 BRT](https://github.com/po-devs/po-web/pull/126#issuecomment-216758857)
> Bold looks a bit goofy with the lean'n'clean look of the webclient :x
> Fuzzysqurl reacted with thumbs up emoji

And the rainbow mode in userlist activated by default, is not "goofy"? Bold names "are goofy" only because is me proposing it?

**Comment by Fuzzysqurl** [comment]
No, its goofy because no other client uses it.

**Comment by danimesq** [comment]
Ok, ok. As you want. I've now reverted the "goofy" bold commit. Now are not problems to put in this PR. :wink:

**Pull request merged**
