### PR TITLE
#133 Usernames in chat supporting click for show user popunder

### PR DESCRIPTION
**Pull request by danimesq**
The usernames in chat don't support clicks. This need support like in userlist.

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
what are branches???

**Comment by danimesq** [comment]
?

**Comment by coyotte508** [comment]
Only 2 files are relevant with a few changes, and there are more than 10 commits with unrelated icons.

It looks like a really nice feature, but please make a single commit?

(btw I made a dev chat on discord: https://discord.gg/010O1SggVDA5ZTBSc if you want to talk about stuf)

**Comment by turbedi** [comment]
It is now possible to squash all commits into one [before merging](http://puu.sh/ogUc9.png) the PR

**Comment by coyotte508** [comment]
my bad. There's still icons in there unrelated to the PR

**Comment by danimesq** [comment]
@coyotte508, this is an diverge, because Fuzzy ever squash the commits into one, then have a diverge between my branch and po-web master, what cause the commits return. But don't worry, only the changes related to master are merged, thanks to the squash function.

**Comment by danimesq** [comment]
**Note**: I've not tested if this feature works.

**Pull request merged**
